---
repos_mellanox_doca_version: 3.1.0
repos_mellanox_repo_name: mellanox_mlnx_ofed
repos_mellanox_repo_suites: /
repos_mellanox_repo_signed_by: https://mirror.eu.nebius.cloud/nvidia/doca/key.gpg

repos_mellanox_arch_map:
  amd64: amd64
  x86_64: amd64
  arm64: arm64-sbsa
  aarch64: arm64-sbsa

repos_mellanox_repo_uri_map:
  amd64: "https://mirror.eu.nebius.cloud/nvidia/doca/snapshots/{{ repos_mellanox_doca_version }}/noble/amd64/20250805_070037/"
  arm64-sbsa: "https://mirror.eu.nebius.cloud/nvidia/doca/snapshots/{{ repos_mellanox_doca_version }}/noble/arm64-sbsa/20250805_070035/"

repos_cuda_dpkg_arch_map:
  x86_64: x86_64
  aarch64: sbsa

repos_cuda_sha256_map:
  x86_64: "sha256:d2a6b11c096396d868758b86dab1823b25e14d70333f1dfa74da5ddaf6a06dba"
  aarch64: "sha256:6ea7d2737648936820e85677177957a0f6521b840d98eb0bbae0a4f003fa7249"
